### ISSUE TITLE
Interface bug

### ISSUE THREAD

**Issue by ellen-brigance** [pluralsight/git-switch-electron#53] opened 2020-05-26 21:17 UTC
Can't add first repository using the UI. It has to be added in the CLI first, then the adding by UI option is available.

**Comment by parkerholladay** [comment] 2020-05-26 22:17
Thanks for the issue report, @ellen-brigance. Which version of the app do you have installed?

**Comment by parkerholladay** [comment] 2020-05-27 15:22
Duplicate of #51 which has been resolved. Release [1.5.1](https://github.com/pluralsight/git-switch-electron/releases/tag/1.5.1) is available for download with a fix.

**Closed by parkerholladay** 2020-05-27 15:22 UTC
